export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const UPDATE_SEARCH_CITY = "UPDATE_SEARCH_CITY";
export const UPDATE_SEARCH_RESULTS = "UPDATE_SEARCH_RESULTS";
export const UPDATE_SEARCH_FILTERS = "UPDATE_SEARCH_FILTERS";
